### ISSUE TITLE
Prototype Tensorflow Tennis Ball Detection

### ISSUE THREAD

**Issue by RyanTheRobothead** [NIURoverTeam/RoverCoreOS#10]
Tutorials and docs for Find_Object_2D: http://wiki.ros.org/find_object_2d

**Comment by halBRY** [comment]
The documentation for the (semi)working CV with TensorFlow is up :] Also, CV is (semi)working!

**Comment by RyanTheRobothead** [comment]
I'd consider this a successful prototype! We'll close this for now and create a new issue when we want to really dig into implementation.
