### ISSUE TITLE
Urdf Tutorials and Examples

### ISSUE THREAD

**Issue by adugyan** [NIURoverTeam/RoverCoreOS#15]
http://www.theconstructsim.com/ros-projects-robotic-manipulator-part-1-basic-urdf-rviz/

Video and text tutorials of various methods to creat Urdf files

**Comment by RyanTheRobothead** [comment]
@adugyan let's move this to a comment in issue #8. Sorry if there was some confusion

**Comment by RyanTheRobothead** [comment]
Closed as Duplicate.
