### ISSUE TITLE
Create URDF File for Ad Astra

### ISSUE THREAD

**Issue by RyanTheRobothead** [NIURoverTeam/RoverCoreOS#3]
http://wiki.ros.org/urdf/Tutorials

**Comment by adugyan** [comment]
Thanks. I’ll be working on it today

**Comment by adugyan** [comment]
What text editor and file type should I be using for the urdf? I can’t
figure out how to launch this

**Comment by RyanTheRobothead** [comment]
I'd recommend running through some of the tutorials for URDF [here](http://wiki.ros.org/urdf/Tutorials), to get a better understanding of what URDF files are and how you can edit and launch. To actually view them, you're gonna have to be booted into Linux.

**Comment by RyanTheRobothead** [comment]
[STL FILES.zip](https://github.com/NIURoverTeam/RoverCoreOS/files/3096684/STL.FILES.zip)
