### ISSUE TITLE
Update Documentation and Getting Started Guide

### ISSUE THREAD

**Issue by RyanTheRobothead** [NIURoverTeam/RoverCoreOS#4]
Need to update docs to reflect changes to project, including switch from Lunar to Kinetic, use of VMs versus Dual Boot versus WSL, and list of courses to learn things like python, command line/Linux, etc.

**Comment by RyanTheRobothead** [comment]
- [x] Thing that needs to be added: New users for TX2 or Shatterdome need to be added to the sudo, dialout, tty, and i2c groups in order to be able to run all of the various aspects of the package. Logout required after adding for effects to manifest.

- [x] Edit: Also now the docker group.

**Comment by waffleston** [comment]
The Wiki has been set up, and the two files in the `/docs/` folder were imported into it.  Should I remove the `/docs/` folder from the repository?

**Comment by RyanTheRobothead** [comment]
Yeah, no need for duplicates

**Comment by RyanTheRobothead** [comment]
Just took a look at the wiki, it's a great start! Definitely think it'll work better than just having a Doc directory.

**Comment by RyanTheRobothead** [comment]
The bulk of this work is done. Last bits can be fleshed out as needed, as part of the Crash Course development.
