### ISSUE TITLE
Create a Crash Course Curriculum

### ISSUE THREAD

**Issue by RyanTheRobothead** [NIURoverTeam/RoverCoreOS#8]
Need to build out a set of beginner's guides to bring new developers up to speed as quickly as possible.

Things to address:
- [ ] Bash and Linux Development
- [x] Git and GitHub
- [ ] Arduino?
- [x] ROS Tutorials Guide
- [ ] Python
- [ ] Jupyter
- [ ] Development Practices
- [ ] Robotics Example Project
- [ ] Docker and Containerization
- [ ] Tensorflow, Computer Vision, and Machine Learning

Chime in with anything else ya'll think we need to address.

**Comment by adugyan** [comment]
https://www.robotigniteacademy.com/en/path/ros-for-beginners/

**Comment by RyanTheRobothead** [comment]
Git & GitHub: https://guides.github.com/, specifically the **Understanding the GitHub Flow** and **Hello World** tutorials.

**Comment by adugyan** [comment]
https://github.com/adugyan/Bash-and-Linux-Development-/wiki

**Comment by RyanTheRobothead** [comment]
@adugyan can you move that into the wiki and add a link to it on the Wiki Home Page under Crash Course? Thanks!

**Comment by adugyan** [comment]
Yea, I'll do that right now
